<?= $this->headLink()->prependStylesheet($this->basePath('css/singin.css'))?>
<body class="bg-light">
<form class="form-signin">
    <h1 class="h5 mb-3 font-weight-normal">Регистрация</h1>
    <?php
    $form = $this->form;
    $form->prepare();
    echo $this->form()->openTag($form);?>
    <p><?php echo $this->formRow($form->get('login'));?></p>
    <p><?php echo $this->formRow($form->get('position'));?></p>
    <p><?php echo $this->formRow($form->get('password'));?></p>
    <p><?php echo $this->formRow($form->get('password2'));?></p>
    <p><?php echo $this->formRow($form->get('submit'));?>
    <?php echo $this->formRow($form->get('submitCancel'));?></p>
    <?php echo $this->form()->closeTag();?>
</form>
</body>