<?= $this->headLink()->prependStylesheet($this->basePath('css/singin.css'))?>
<body class="text-center">
<form class="form-signin">
    <h1 class="h3 mb-3 font-weight-normal">Изменение пароля</h1>
    <?php
    $form = $this->form;
    $form->prepare();
    echo $this->form()->openTag($form);
    echo $this->formRow($form->get('password'));
    echo $this->formRow($form->get('password2'));?>
    <p><?php echo $this->formRow($form->get('submit'));
        echo $this->formRow($form->get('submitCancel'));?></p>
    <?php echo $this->form()->closeTag($form);?>
</body>