<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Information portal')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink()
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->inlineScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.3.1.min.js'))
        ?>
        <style>
            .bd-placeholder-img {
                font-size: 1.125rem;
                text-anchor: middle;
                -webkit-user-select: none;
                -moz-user-select: none;
                -ms-user-select: none;
                user-select: none;
            }

            @media (min-width: 768px) {
                .bd-placeholder-img-lg {
                    font-size: 3.5rem;
                }
            }
        </style>

    </head>
    <body>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top navbar_color">
        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="<?php echo $this-> url('user', array('action'=> 'index'));?>">Главная</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="<?php echo $this-> url('user', array('action'=> 'userinformation'));?>">Профиль</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="<?php echo $this-> url('user', array('action'=> 'listmessages'));?>">Сообщения</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="<?php echo $this-> url('user', array('action'=> 'listusers'));?>">Пользователи</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="<?php echo $this-> url('entrance', array('action'=> 'index'));?>">Выйти</a>
                </li>
            </ul>
        </div>
    </nav>
        <div class="container">
            <?= $this->content?>

        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
