<?= $this->headLink()->prependStylesheet($this->basePath('css/singin.css'))
?>
<body class="text-center">
<form class="form-signin">
    <h1 class="h3 mb-3 font-weight-normal">Change position</h1>
    <?php $form = $this->form;
    $form->prepare();
    echo $this->form()->openTag($form);
    echo $this->formRow($form->get('position'));?>
    <div>
        <?php echo $this->formSubmit($form->get('submit'));
        echo $this->formSubmit($form->get('submitCancel'));
        echo $this->form()->closeTag();?>
    </div>
</form>
</body>